-- CREATE TABLE "events" (
-- 	"id" serial PRIMARY KEY NOT NULL,
-- 	"name" varchar(200) NOT NULL,
-- 	"description" text,
-- 	"date" timestamp NOT NULL,
-- 	"location" varchar(255),
-- 	"event_code" varchar(50) NOT NULL,
-- 	"access_code" varchar(50) NOT NULL,
-- 	"team_id" integer NOT NULL,
-- 	"created_by" integer NOT NULL,
-- 	"is_public" boolean DEFAULT false NOT NULL,
-- 	"allow_guest_uploads" boolean DEFAULT true NOT NULL,
-- 	"require_approval" boolean DEFAULT false NOT NULL,
-- 	"created_at" timestamp DEFAULT now() NOT NULL,
-- 	"updated_at" timestamp DEFAULT now() NOT NULL,
-- 	CONSTRAINT "events_event_code_unique" UNIQUE("event_code"),
-- 	CONSTRAINT "events_access_code_unique" UNIQUE("access_code")
-- );
--> statement-breakpoint
-- CREATE TABLE "photos" (
-- 	"id" serial PRIMARY KEY NOT NULL,
-- 	"filename" varchar(255) NOT NULL,
-- 	"original_filename" varchar(255) NOT NULL,
-- 	"mime_type" varchar(100) NOT NULL,
-- 	"file_size" integer NOT NULL,
-- 	"file_path" text NOT NULL,
-- 	"event_id" integer NOT NULL,
-- 	"uploaded_by" integer,
-- 	"guest_name" varchar(100),
-- 	"guest_email" varchar(255),
-- 	"is_approved" boolean DEFAULT true NOT NULL,
-- 	"uploaded_at" timestamp DEFAULT now() NOT NULL
-- );
-- --> statement-breakpoint
-- CREATE TABLE "verification_tokens" (
-- 	"id" serial PRIMARY KEY NOT NULL,
-- 	"user_id" integer NOT NULL,
-- 	"token" varchar(255) NOT NULL,
-- 	"expires_at" timestamp NOT NULL,
-- 	"created_at" timestamp DEFAULT now() NOT NULL,
-- 	CONSTRAINT "verification_tokens_token_unique" UNIQUE("token")
-- );
--> statement-breakpoint

ALTER TABLE "users" ADD COLUMN "plan_name" varchar(50);--> statement-breakpoint
